// <auto-generated />
using System;
using AllReady.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AllReady.Api.Migrations
{
    [DbContext(typeof(AllReadyDbContext))]
    partial class AllReadyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AllReady.Api.Data.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<string>("ExternalUrl");

                    b.Property<string>("ExternalUrlText");

                    b.Property<string>("FullDescription");

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("IsFeatured");

                    b.Property<string>("Name");

                    b.Property<string>("PostalCode");

                    b.Property<string>("ShortDescription");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<string>("State");

                    b.Property<string>("TimeZone");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
